[package]
name = "competitive-tools-rust"
version = "0.6.2"
authors = ["UseK <use.k.james@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0"