[package]
name = "competitive-tools-rust"
version = "0.9.2"
authors = ["UseK <use.k.james@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0"
num = "0.4.0"
